"""One-off: append Wave J + Wave K rows to I86 files-modified.csv.

Per akos-planning-traceability.mdc per-initiative file-changes CSV mandate.
Wave K commit_sha is filled in post-commit (placeholder 'wave-k-pending' for now).
Wave J entries also backfilled (sha was missed in Wave J commit).
"""
from __future__ import annotations
import csv
import io
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = (
    ROOT
    / "docs"
    / "wip"
    / "planning"
    / "86-initiative-cluster-execution-coordinator"
    / "files-modified.csv"
)

WAVE_K_DATE = "2026-05-20"
WAVE_K_SHA = "wave-k-pending"
WAVE_K_PHASE = "Wave-K"

DECISIONS = "D-IH-86-AY;D-IH-86-AZ;D-IH-86-BA;D-IH-86-BB;D-IH-86-BC;D-IH-86-BD"

ROWS = [
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+1/-1",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/Compliance/canonicals/dimensions/AUDIENCE_REGISTRY.csv",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BD",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "AUDIENCE_REGISTRY.csv;PRECEDENCE.md",
        "validate_hlk.py",
        "yes",
        "Mint J-AIC row to resolve dangling FK references in Wave I/J cross-references; updated J-OP notes to separate AICs.",
        "Wave K K1 mechanical fix per D-IH-86-BD",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+12/-2",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/canonicals/HOLISTIKA_QUALITY_FABRIC.md",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-AZ;D-IH-86-BA;D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "HOLISTIKA_QUALITY_FABRIC.md;OUTPUT_TYPE_LIBRARY.md;ARTIFACT_CLASS_LIBRARY.md;COMPONENT_PRIMITIVE_LIBRARY.md",
        "",
        "no",
        "Add 4-layer hierarchy reference (3.1); extend materialisation table 5->9 specialties (6); add compose() runbook gating as gate item 4 (10).",
        "Wave K K4",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+15/-0",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/canonicals/UAT_DISCIPLINE.md",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-AY",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "UAT_DISCIPLINE.md",
        "",
        "no",
        "Promote 7-class UAT taxonomy to 11 classes (adds localisation/accessibility/performance/privacy classes).",
        "Wave K K5",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+6/-0",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/Compliance/canonicals/DECISION_REGISTER.csv",
        "canonical",
        "Founder",
        "Admin",
        "Holistika",
        DECISIONS,
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "DECISION_REGISTER.csv;HOLISTIKA_QUALITY_FABRIC.md;UAT_DISCIPLINE.md",
        "validate_decision_register.py",
        "yes",
        "Append D-IH-86-AY through D-IH-86-BD (6 decisions: UAT 11-class promote; fabric materialisation 5->9; compose() gating; 4-layer architecture; I-NN-OUTPUT-ARCHITECTURE charter; J-AIC mint).",
        "Wave K K2 via scripts/_one_off/append_wave_k_decisions.py",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+18/n_a",
        "openclaw-akos",
        "docs/wip/planning/_candidates/i-nn-output-architecture.md",
        "planning",
        "System Owner",
        "Tech",
        "Holistika",
        "D-IH-86-BC",
        "",
        "_candidates/i-nn-output-architecture.md",
        "",
        "no",
        "Mint candidate file for I-NN-OUTPUT-ARCHITECTURE; supersedes the previously-named I-NN-MESSAGE-COMPONENT-LIBRARY single-axis framing.",
        "Wave K K3",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+18/n_a",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/Compliance/canonicals/dimensions/OUTPUT_TYPE_REGISTRY.csv",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "OUTPUT_TYPE_REGISTRY.csv;OUTPUT_TYPE_LIBRARY.md;PRECEDENCE.md",
        "",
        "yes",
        "Mint Layer 1 canonical CSV (17 rows; 14 active + 2 planned + 1 active-skeleton) covering prose/slide/image/voice/mermaid/gantt/excalidraw/web/pdf/video/audio output types.",
        "Wave K K6",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+22/n_a",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/Compliance/canonicals/dimensions/ARTIFACT_CLASS_REGISTRY.csv",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "ARTIFACT_CLASS_REGISTRY.csv;ARTIFACT_CLASS_LIBRARY.md;OUTPUT_TYPE_REGISTRY.csv;PRECEDENCE.md",
        "",
        "yes",
        "Mint Layer 2 canonical CSV (21 rows; 20 active + 1 planned) covering dossier/cover-email/intro-message/decks/UAT-report/SOP/runbook/canonical-CSV/decision-row/initiative-charter/dashboard purposes; all 11 render scripts + 2 export scripts classified.",
        "Wave K K7 + K10",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+26/n_a",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/Compliance/canonicals/dimensions/COMPONENT_PRIMITIVE_REGISTRY.csv",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "COMPONENT_PRIMITIVE_REGISTRY.csv;COMPONENT_PRIMITIVE_LIBRARY.md;ARTIFACT_CLASS_REGISTRY.csv;PRECEDENCE.md",
        "",
        "yes",
        "Mint Layer 3 canonical CSV (25 rows) covering Shadcn-shape primitives spanning prose (greeting/hook/body/CTA/signature/evidence/methodology) + visual (slide-hero/slide-compare/mermaid/gantt/cover-page) + interactive (form-field/dashboard-card/navbar/sidebar/empty-state/loading-state/error-state) kinds.",
        "Wave K K8",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+200/n_a",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/canonicals/OUTPUT_TYPE_LIBRARY.md",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "OUTPUT_TYPE_LIBRARY.md;OUTPUT_TYPE_REGISTRY.csv;PRECEDENCE.md",
        "",
        "no",
        "Mint Layer 1 narrative companion library (8-section per-output-type contract; OT-PROSE-EMAIL-RICH worked exemplar; forward-charter for 16 remaining doctrine pages).",
        "Wave K K6",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+220/n_a",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/canonicals/ARTIFACT_CLASS_LIBRARY.md",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "ARTIFACT_CLASS_LIBRARY.md;ARTIFACT_CLASS_REGISTRY.csv;COMPONENT_PRIMITIVE_LIBRARY.md;OUTPUT_TYPE_LIBRARY.md;PRECEDENCE.md",
        "",
        "no",
        "Mint Layer 2 narrative companion library (7-section per-artifact-class contract; AC-COVER-EMAIL worked exemplar with full 6-audience composition matrix per primitive slot).",
        "Wave K K7",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+260/n_a",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/canonicals/COMPONENT_PRIMITIVE_LIBRARY.md",
        "canonical",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "COMPONENT_PRIMITIVE_LIBRARY.md;COMPONENT_PRIMITIVE_REGISTRY.csv;ARTIFACT_CLASS_LIBRARY.md;PRECEDENCE.md",
        "",
        "no",
        "Mint Layer 3 narrative companion library (9-section Shadcn-shape per-primitive contract; CP-CTA worked exemplar with 8 variants x 6-audience composition x 8 anti-patterns + open-code templates for mail/DM/web React; cites Shadcn Button + HeroUI + Stripe + Linear + BasecampForms external precedents).",
        "Wave K K8",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+15/-15",
        "openclaw-akos",
        "docs/references/hlk/v3.0/_assets/touchpoint-kit/",
        "data",
        "Brand & Narrative Manager",
        "Marketing",
        "Holistika",
        "D-IH-86-BB",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "OUTPUT_TYPE_REGISTRY.csv;ARTIFACT_CLASS_REGISTRY.csv;COMPONENT_PRIMITIVE_REGISTRY.csv",
        "",
        "no",
        "Backfill 15 intro-message files with output_type_source/render + artifact_class:AC-INTRO-MESSAGE + component_primitive_inventory + layered_architecture_version frontmatter.",
        "Wave K K9 via scripts/_one_off/backfill_touchpoint_kit_layered_frontmatter.py",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+6/-0",
        "openclaw-akos",
        "docs/references/hlk/v3.0/Admin/O5-1/People/Compliance/canonicals/PRECEDENCE.md",
        "canonical",
        "System Owner",
        "Admin",
        "Holistika",
        "D-IH-86-BB;D-IH-86-BD",
        "tbi_mkt_prc_brand_canon_mtnce_001",
        "PRECEDENCE.md;OUTPUT_TYPE_REGISTRY.csv;ARTIFACT_CLASS_REGISTRY.csv;COMPONENT_PRIMITIVE_REGISTRY.csv;OUTPUT_TYPE_LIBRARY.md;ARTIFACT_CLASS_LIBRARY.md;COMPONENT_PRIMITIVE_LIBRARY.md",
        "",
        "yes",
        "Register 6 new canonical entries (3 CSVs + 3 libraries) for the 4-layer output architecture.",
        "Wave K K11",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+1/-0",
        "openclaw-akos",
        "CHANGELOG.md",
        "changelog",
        "System Owner",
        "Tech",
        "Holistika",
        "D-IH-86-BB;D-IH-86-BD",
        "",
        "DECISION_REGISTER.csv;PRECEDENCE.md;HOLISTIKA_QUALITY_FABRIC.md",
        "",
        "no",
        "Prepended Wave K entry to [Unreleased].",
        "Wave K K11",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+25/-0",
        "openclaw-akos",
        "docs/wip/planning/86-initiative-cluster-execution-coordinator/master-roadmap.md",
        "planning",
        "System Owner",
        "Operations",
        "Holistika",
        "D-IH-86-BB;D-IH-86-BD",
        "",
        "master-roadmap.md;CHANGELOG.md;DECISION_REGISTER.csv",
        "",
        "no",
        "Add 1.9 Wave K narrative section after 1.8 Wave J.",
        "Wave K K11",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+150/n_a",
        "openclaw-akos",
        "scripts/_one_off/append_wave_k_decisions.py",
        "script",
        "System Owner",
        "Tech",
        "Holistika",
        "D-IH-86-AY;D-IH-86-AZ;D-IH-86-BA;D-IH-86-BB;D-IH-86-BC;D-IH-86-BD",
        "",
        "DECISION_REGISTER.csv",
        "",
        "no",
        "One-off Python script to append 6 Wave K decision rows to DECISION_REGISTER.csv with proper csv.writer escaping.",
        "Wave K K2 tooling",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "created",
        "+95/n_a",
        "openclaw-akos",
        "scripts/_one_off/backfill_touchpoint_kit_layered_frontmatter.py",
        "script",
        "System Owner",
        "Tech",
        "Holistika",
        "D-IH-86-BB",
        "",
        "touchpoint-kit/*",
        "",
        "no",
        "One-off Python script to backfill 15 touchpoint-kit intro-message files with 4-layer architecture frontmatter (output_type_source/render + AC-INTRO-MESSAGE + component_primitive_inventory + layered_architecture_version).",
        "Wave K K9 tooling",
    ],
    [
        WAVE_K_PHASE,
        WAVE_K_SHA,
        WAVE_K_DATE,
        "modified",
        "+18/-0",
        "openclaw-akos",
        "docs/wip/planning/86-initiative-cluster-execution-coordinator/files-modified.csv",
        "planning",
        "System Owner",
        "Operations",
        "Holistika",
        "D-IH-86-BB",
        "",
        "files-modified.csv",
        "",
        "no",
        "Append Wave K rows for the 4-layer output architecture landing.",
        "Wave K K11 self-reference",
    ],
]


def main() -> None:
    if not CSV_PATH.exists():
        raise SystemExit(f"Not found: {CSV_PATH}")

    existing = CSV_PATH.read_text(encoding="utf-8")
    if not existing.endswith("\n"):
        existing += "\n"

    out_lines = []
    for row in ROWS:
        sio = io.StringIO()
        w = csv.writer(sio, lineterminator="", quoting=csv.QUOTE_MINIMAL)
        w.writerow(row)
        out_lines.append(sio.getvalue())

    CSV_PATH.write_text(existing + "\n".join(out_lines) + "\n", encoding="utf-8")
    print(f"Appended {len(ROWS)} rows; final size {CSV_PATH.stat().st_size} bytes")


if __name__ == "__main__":
    main()
