#!/usr/bin/env python3
"""People Cross-Area Breakthrough Propagation runbook (Initiative 79 P4).

Paired runbook for ``SOP-PEOPLE_CROSS_AREA_BREAKTHROUGH_001.md`` per
[`akos-executable-process-catalog.mdc`](../.cursor/rules/akos-executable-process-catalog.mdc)
Rule 1. Implements the cross-area announcement cadence described in the SOP §2.

Reads ``PEOPLE_DESIGN_PATTERN_REGISTRY.csv``, filters rows revised after
``--since`` (or revised during a given ``--quarter``), groups by
``consumer_areas``, and emits per-area Markdown digests under
``docs/wip/planning/79-people-manifesto-and-pattern-library/reports/breakthroughs/<YYYY-MM>/<area>.md``.

Each digest carries: pattern_id + name + summary; acceptance criteria for
both human and automation paths; link to the ``#pattern-<slug>`` anchor in
``PEOPLE_DESIGN_PATTERN_LIBRARY.md``; link to the registry row's
``canonical_artifact_path``; a placeholder line where People Operations Manager
hand-authors a "what this means for your area" rendering before circulating.

Cross-references:

- ``SOP-PEOPLE_CROSS_AREA_BREAKTHROUGH_001.md`` (paired SOP).
- ``PEOPLE_DESIGN_PATTERN_REGISTRY.csv`` (SSOT this runbook reads).
- ``akos-executable-process-catalog.mdc`` Rule 1 (pairing rule).
- ``process_list.csv`` row ``tbi_peopl_dtp_cross_area_breakthrough_001``
  (this is the paired runbook for that event-triggered cadence row).

Usage::

    py scripts/peopl_cross_area_breakthrough_announce.py --since 2026-04-01
    py scripts/peopl_cross_area_breakthrough_announce.py --reconcile --quarter 2026-Q2
    py scripts/peopl_cross_area_breakthrough_announce.py --dry-run --since 2026-05-01

Per ``CONTRIBUTING.md`` Python Code Standards: type hints + structured logging
+ ``pathlib.Path`` + stdlib-only.

Exit code 0 PASS, 1 FAIL.
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import logging
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

REGISTRY_CSV = (
    REPO_ROOT
    / "docs"
    / "references"
    / "hlk"
    / "v3.0"
    / "Admin"
    / "O5-1"
    / "People"
    / "Compliance"
    / "canonicals"
    / "dimensions"
    / "PEOPLE_DESIGN_PATTERN_REGISTRY.csv"
)

DIGEST_ROOT = (
    REPO_ROOT
    / "docs"
    / "wip"
    / "planning"
    / "79-people-manifesto-and-pattern-library"
    / "reports"
    / "breakthroughs"
)

CONSUMER_AREA_TOKENS = (
    "marketing",
    "research",
    "techlab",
    "operations",
    "legal",
    "compliance",
    "ethics",
    "finance",
    "people",
    "all",
)

logger = logging.getLogger("peopl_cross_area_breakthrough_announce")


def _parse_since(value: str | None) -> dt.date | None:
    if not value:
        return None
    return dt.date.fromisoformat(value)


def _parse_quarter(quarter: str) -> tuple[dt.date, dt.date]:
    """Parse a quarter token (e.g. ``2026-Q2``) to (start, end) inclusive."""
    match = re.match(r"^(\d{4})-Q([1-4])$", quarter)
    if not match:
        raise ValueError(f"invalid quarter token: {quarter!r}; expected YYYY-Q[1-4]")
    year = int(match.group(1))
    q = int(match.group(2))
    start_month = 1 + 3 * (q - 1)
    end_month = start_month + 2
    start = dt.date(year, start_month, 1)
    if end_month == 12:
        end = dt.date(year, 12, 31)
    else:
        end = dt.date(year, end_month + 1, 1) - dt.timedelta(days=1)
    return (start, end)


def _row_in_window(row_date: str, *, since: dt.date | None, until: dt.date | None) -> bool:
    """Return True when the row's last_review date falls in the [since, until] window."""
    try:
        row_iso = dt.date.fromisoformat(row_date)
    except ValueError:
        return False
    if since is not None and row_iso < since:
        return False
    if until is not None and row_iso > until:
        return False
    return True


def _expand_consumer_areas(cell: str) -> list[str]:
    """Split a semicolon-list of consumer-area tokens; expand 'all' to the canonical set."""
    raw = [token.strip().lower() for token in cell.split(";") if token.strip()]
    if "all" in raw:
        return [a for a in CONSUMER_AREA_TOKENS if a != "all"]
    return [a for a in raw if a in CONSUMER_AREA_TOKENS]


def _per_area_digest_body(rows: list[dict[str, str]], *, area: str) -> str:
    """Render per-area digest Markdown from filtered registry rows."""
    body: list[str] = [
        f"# Cross-area breakthrough digest — {area.title()}",
        "",
        "_Auto-generated by `scripts/peopl_cross_area_breakthrough_announce.py`. "
        "People Operations Manager authors the per-pattern \"what this means for your area\" line before circulating._",
        "",
        f"- Total patterns since last announcement: {len(rows)}",
        "",
        "## Patterns",
        "",
    ]
    for row in rows:
        pattern_id = row.get("pattern_id", "<unknown>")
        pattern_name = row.get("pattern_name", "<unnamed>")
        anchor = row.get("pattern_md_anchor", "")
        canonical_path = row.get("canonical_artifact_path", "")
        ach = row.get("acceptance_criteria_human", "")
        aca = row.get("acceptance_criteria_automation", "")
        status = row.get("status", "")
        last_review = row.get("last_review", "")
        body.extend(
            [
                f"### {pattern_name} (`{pattern_id}`)",
                "",
                f"- Status: `{status}`; last review: `{last_review}`.",
                f"- Library anchor: [`{anchor}`](../../../../../docs/references/hlk/v3.0/Admin/O5-1/People/canonicals/PEOPLE_DESIGN_PATTERN_LIBRARY.md{anchor}).",
                f"- Canonical artefact: `{canonical_path}`.",
                "- Acceptance criteria (human path):",
                "",
                f"  > {ach}",
                "",
                "- Acceptance criteria (automation path):",
                "",
                f"  > {aca}",
                "",
                "- **What this means for your area** (People Operations Manager authors at announcement time): _<placeholder>_.",
                "",
                "- Decision (your area's role-owner records here): adopt-now / adopt-later / decline.",
                "",
                "---",
                "",
            ]
        )
    return "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit per-area breakthrough digests from PEOPLE_DESIGN_PATTERN_REGISTRY.csv."
    )
    parser.add_argument(
        "--since",
        type=str,
        default=None,
        help="ISO date (YYYY-MM-DD); include rows with last_review on or after this date",
    )
    parser.add_argument(
        "--reconcile",
        action="store_true",
        help="quarterly reconciliation mode (use with --quarter)",
    )
    parser.add_argument(
        "--quarter",
        type=str,
        default=None,
        help="quarter token (YYYY-Q[1-4]); used with --reconcile",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="parse + filter but do not write digest files",
    )
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=log_level, format="%(levelname)s | %(message)s")

    if not REGISTRY_CSV.exists():
        logger.error("FAIL: registry CSV not found at %s", REGISTRY_CSV)
        return 1

    since = _parse_since(args.since) if args.since else None
    until: dt.date | None = None
    quarter_label = ""
    if args.reconcile:
        if not args.quarter:
            logger.error("FAIL: --reconcile requires --quarter")
            return 1
        since, until = _parse_quarter(args.quarter)
        quarter_label = args.quarter

    if since is None and not args.reconcile:
        logger.error("FAIL: pass --since YYYY-MM-DD or --reconcile --quarter YYYY-Q[1-4]")
        return 1

    with REGISTRY_CSV.open("r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        all_rows = list(reader)

    rows_in_window = [
        row for row in all_rows if _row_in_window(row.get("last_review", ""), since=since, until=until)
    ]
    logger.info(
        "registry rows in window [%s..%s]: %s of %s",
        since.isoformat() if since else "-inf",
        until.isoformat() if until else "+inf",
        len(rows_in_window),
        len(all_rows),
    )

    by_area: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows_in_window:
        for area in _expand_consumer_areas(row.get("consumer_areas", "")):
            by_area[area].append(row)

    if not by_area:
        logger.info("OVERALL PASS: no rows in window; no digests to emit")
        return 0

    today = dt.date.today()
    digest_subdir = quarter_label if quarter_label else today.strftime("%Y-%m")
    digest_dir = DIGEST_ROOT / digest_subdir
    if not args.dry_run:
        digest_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for area, rows in sorted(by_area.items()):
        body = _per_area_digest_body(rows, area=area)
        digest_path = digest_dir / f"{area}.md"
        if args.dry_run:
            logger.info("DRY RUN: would write %s (%s rows)", digest_path.relative_to(REPO_ROOT), len(rows))
            continue
        digest_path.write_text(body + "\n", encoding="utf-8")
        written.append(digest_path)
        logger.info("wrote %s (%s rows)", digest_path.relative_to(REPO_ROOT), len(rows))

    logger.info("OVERALL PASS: %s areas processed; %s files written", len(by_area), len(written))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
