#!/usr/bin/env python3
"""Regenerate consumer-side TypeScript types from the AKOS canonical mirrors.

For repos in ``REPOSITORY_REGISTRY.csv`` with
``consumes_compliance_types=yes`` (I63 column), this script:

1. Determines the local working tree (via ``path`` column or ``--repo-path-map``).
2. Runs ``npx supabase gen types typescript --linked`` (when ``supabase`` CLI is
   present and the repo has ``supabase/migrations/``) and writes to
   ``<repo>/lib/supabase/database.types.ts``.
3. As a CSV-driven fallback (no Supabase login required), reads the
   ``consumes_mirrors`` field and emits hand-rolled TypeScript interfaces from
   the corresponding ``compliance.*_mirror`` CSVs in AKOS into
   ``<repo>/lib/types/akos-mirrors.generated.ts``.
4. Compares the regenerated output against the on-disk file. When drift is
   detected and ``--auto-pr`` is passed, opens a PR via ``gh`` against the
   consumer.

This is the bridge that lets consumers stay strictly typed against AKOS without
hand-editing types when canonical CSVs grow new columns.

Usage::

    py scripts/regen_consumer_types.py --repo-slug hlk-erp
    py scripts/regen_consumer_types.py --repo-slug hlk-erp --auto-pr
    py scripts/regen_consumer_types.py            # all consuming repos
"""

from __future__ import annotations

import argparse
import csv
import logging
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from akos.io import REPO_ROOT
from akos.log import setup_logging
from scripts.bless_external_repo import (
    REFERENCE_CLASS,
    RepoMeta,
    load_registry,
    sha256_text,
)

logger = logging.getLogger("akos.regen_types")

COMPLIANCE_DIR = REPO_ROOT / "docs" / "references" / "hlk" / "v3.0" / "Admin" / "O5-1" / "People" / "Compliance" / "canonicals"


def _ts_safe_name(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s)


def _csv_to_interface(csv_path: Path, interface_name: str) -> str:
    """Emit a TypeScript interface from a CSV header row.

    All fields typed as ``string | null`` to stay schema-tolerant; consumers
    can refine specific columns in their own .d.ts.
    """
    if not csv_path.is_file():
        return f"// missing source: {csv_path.name}\nexport interface {interface_name} {{}}\n"
    with csv_path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.reader(fh)
        try:
            headers = next(reader)
        except StopIteration:
            headers = []
    lines = [f"export interface {interface_name} {{"]
    for h in headers:
        col = h.strip().replace('"', "")
        if not col:
            continue
        prop = col if col.replace("_", "").isalnum() else f'"{col}"'
        lines.append(f"  {prop}: string | null")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_mirrors_module(meta: RepoMeta) -> str:
    """Render the ``akos-mirrors.generated.ts`` body from the consumed mirrors."""
    header = (
        "// AUTO-GENERATED by scripts/regen_consumer_types.py from AKOS canonical CSVs.\n"
        "// Do not hand-edit. Run the regen script (or wait for the nightly auto-PR)\n"
        "// when an AKOS canonical CSV grows new columns.\n\n"
    )
    if not meta.consumes_mirrors:
        return header + "// No mirrors declared in REPOSITORY_REGISTRY.consumes_mirrors.\n"
    blocks: list[str] = [header]
    for mirror in meta.consumes_mirrors:
        csv_path = COMPLIANCE_DIR / f"{mirror}.csv"
        iface = "AkosMirror_" + _ts_safe_name(mirror)
        try:
            origin = csv_path.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            origin = csv_path.name
        blocks.append(f"// from {origin}\n" + _csv_to_interface(csv_path, iface))
    return "\n".join(blocks)


def _resolve_repo_path(meta: RepoMeta, override_map: dict[str, Path]) -> Path | None:
    if meta.slug in override_map:
        return override_map[meta.slug]
    if meta.relative_path:
        cand = (REPO_ROOT.parent / meta.relative_path).resolve()
        if cand.is_dir():
            return cand
    return None


def regen_one(meta: RepoMeta, repo_path: Path, *, dry_run: bool, auto_pr: bool) -> str:
    if not meta.consumes_compliance_types:
        return "SKIPPED_NOT_CONSUMING"
    rendered = render_mirrors_module(meta)
    target = repo_path / "lib" / "types" / "akos-mirrors.generated.ts"
    on_disk = target.read_text(encoding="utf-8") if target.is_file() else ""
    if sha256_text(on_disk) == sha256_text(rendered):
        return "ALIGNED"
    if dry_run:
        logger.info("[dry-run] would update %s", target)
        return "DRY_WROTE"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    logger.info("regenerated %s", target)

    if auto_pr and shutil.which("gh") is not None:
        repo_arg = meta.github_url.replace("https://github.com/", "")
        title = "chore(types): regenerate AKOS mirror types"
        body = (
            "Auto-regenerated TypeScript interfaces from AKOS canonical CSVs.\n\n"
            f"Mirrors: {', '.join(meta.consumes_mirrors)}\n\n"
            "Source: https://github.com/FraysaXII/openclaw-akos/tree/main/docs/references/hlk/v3.0/Admin/O5-1/People/Compliance/canonicals/\n"
        )
        try:
            subprocess.run(
                ["gh", "pr", "create", "--repo", repo_arg, "--title", title, "--body", body, "--base", "main"],
                capture_output=True, text=True, timeout=60, cwd=repo_path, check=False,
            )
        except Exception as exc:
            logger.warning("auto-PR failed: %s", exc)
    return "REGENERATED"


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regen TS types for compliance-consuming repos")
    parser.add_argument("--repo-slug")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--auto-pr", action="store_true")
    parser.add_argument(
        "--repo-path-map",
        action="append",
        default=[],
        help="Per-repo path override, e.g. hlk-erp=C:/abs/path. Repeatable.",
    )
    parser.add_argument("--json-log", action="store_true")
    args = parser.parse_args(list(argv) if argv is not None else None)
    setup_logging(json_output=args.json_log)

    overrides: dict[str, Path] = {}
    for entry in args.repo_path_map:
        if "=" not in entry:
            continue
        slug, path_str = entry.split("=", 1)
        overrides[slug.strip()] = Path(path_str.strip()).resolve()

    registry = load_registry()
    slugs = [args.repo_slug] if args.repo_slug else [
        s for s, m in registry.items()
        if m.repo_class.lower() != REFERENCE_CLASS
        and "openclaw-akos" not in m.github_url
        and m.consumes_compliance_types
    ]

    overall_ok = True
    for slug in slugs:
        meta = registry.get(slug)
        if meta is None:
            logger.warning("unknown slug %s", slug)
            continue
        repo_path = _resolve_repo_path(meta, overrides)
        if repo_path is None:
            print(f"  [{'NO_PATH':>22}] {slug}")
            continue
        outcome = regen_one(meta, repo_path, dry_run=args.dry_run, auto_pr=args.auto_pr)
        print(f"  [{outcome:>22}] {slug}")
        if outcome.startswith("FAILED"):
            overall_ok = False

    return 0 if overall_ok else 1


if __name__ == "__main__":
    sys.exit(main())
