#!/usr/bin/env python3
"""Initiative 25 P3: deterministic topic-graph renderer.

Reads `docs/references/hlk/compliance/dimensions/TOPIC_REGISTRY.csv` and
emits `_assets/_meta/topic_graph.{mmd,png,svg}` showing all topics + edges
+ program clusters (subgraphs by `program_id`).

Reuses `scripts/render_km_diagrams.py` for the PNG/SVG rendering pipeline
(mmdc preferred, mermaid.ink HTTP fallback). The CSV is SSOT; this script
is read-only.

Usage::

    py scripts/render_topic_graph.py            # write all 3 files
    py scripts/render_topic_graph.py --dry-run  # print Mermaid; no writes
"""

from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from akos.io import REPO_ROOT as IO_REPO_ROOT  # noqa: E402,F401

CSV_PATH = REPO_ROOT / "docs" / "references" / "hlk" / "compliance" / "dimensions" / "TOPIC_REGISTRY.csv"
META_DIR = REPO_ROOT / "docs" / "references" / "hlk" / "v3.0" / "_assets" / "_meta"
MMD_PATH = META_DIR / "topic_graph.mmd"
RENDER_SCRIPT = REPO_ROOT / "scripts" / "render_km_diagrams.py"


def _safe_id(value: str) -> str:
    """Mermaid identifier: ASCII-only, no spaces/punctuation."""
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in value or "")


def _split(value: str) -> list[str]:
    return [p.strip() for p in (value or "").split(";") if p.strip()]


def build_mermaid(rows: list[dict[str, str]]) -> str:
    """Build a Mermaid `flowchart LR` from TOPIC_REGISTRY rows.

    Topics are clustered into subgraphs by `program_id` (with a separate
    `shared` cluster for cross-program topics). Edges:

    - parent_topic     -> ``--->`` (solid, thick)
    - depends_on       -> ``-.->`` (dashed)
    - related_topics   -> ``---``  (undirected line)
    - subsumes         -> ``==>``  (heavy)

    Colors are intentionally omitted; the structure carries the meaning.
    """
    lines: list[str] = []
    lines.append("%% Topic graph (Initiative 25 P3)")
    lines.append(f"%% Generated by scripts/render_topic_graph.py from {CSV_PATH.relative_to(REPO_ROOT).as_posix()}")
    lines.append("%% Do NOT hand-edit; regenerate via `py scripts/render_topic_graph.py`.")
    lines.append("flowchart LR")

    by_program: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        prog = (row.get("program_id") or "shared").strip() or "shared"
        by_program.setdefault(prog, []).append(row)

    for prog, prog_rows in sorted(by_program.items()):
        cluster_id = _safe_id(prog) or "shared"
        lines.append(f"  subgraph {cluster_id} [{prog}]")
        for row in sorted(prog_rows, key=lambda r: r.get("topic_id", "")):
            tid = (row.get("topic_id") or "").strip()
            if not tid:
                continue
            label = (row.get("title") or tid).replace('"', '\\"')
            klass = (row.get("topic_class") or "").strip()
            shape = "[" if klass != "evidence_pack" else "(["
            shape_close = "]" if klass != "evidence_pack" else "])"
            lines.append(f'    {_safe_id(tid)}{shape}"{label}"{shape_close}')
        lines.append("  end")

    for row in rows:
        tid = (row.get("topic_id") or "").strip()
        if not tid:
            continue
        sid = _safe_id(tid)
        parent = (row.get("parent_topic") or "").strip()
        if parent:
            lines.append(f"  {_safe_id(parent)} --> {sid}")
        for ref in _split(row.get("depends_on", "")):
            lines.append(f"  {sid} -.-> {_safe_id(ref)}")
        for ref in _split(row.get("related_topics", "")):
            lines.append(f"  {sid} --- {_safe_id(ref)}")
        for ref in _split(row.get("subsumes", "")):
            lines.append(f"  {sid} ==> {_safe_id(ref)}")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--dry-run", action="store_true", help="Print Mermaid to stdout without writing")
    args = parser.parse_args(argv)

    if not CSV_PATH.is_file():
        sys.stderr.write(f"render_topic_graph: missing {CSV_PATH}\n")
        return 2

    with CSV_PATH.open(encoding="utf-8", newline="") as fh:
        rows = [dict(r) for r in csv.DictReader(fh)]

    mmd = build_mermaid(rows)

    if args.dry_run:
        sys.stdout.write(mmd)
        return 0

    META_DIR.mkdir(parents=True, exist_ok=True)
    MMD_PATH.write_text(mmd, encoding="utf-8")
    print(f"render_topic_graph: wrote {MMD_PATH.relative_to(REPO_ROOT)} ({len(mmd)} chars)")

    rc = subprocess.run(
        [sys.executable, str(RENDER_SCRIPT), str(MMD_PATH)],
        text=True,
    ).returncode
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
