#!/usr/bin/env python3
"""Initiative 25 P5: render PMO hub stakeholder index between auto-gen markers.

Reads canonical CSVs (`GOI_POI_REGISTER`, `ADVISER_ENGAGEMENT_DISCIPLINES`,
`PROGRAM_REGISTRY`, `ADVISER_OPEN_QUESTIONS`) and emits the **stakeholder index
table** of `TOPIC_PMO_CLIENT_DELIVERY_HUB.md` between dedicated auto-gen markers.

Per Wave-2 plan §"Auto-generated section contract":

- **Markers** (HTML comments):
  ``<!-- BEGIN_AUTOGEN section_id=pmo_stakeholder_index_v1 generated_by=scripts/render_pmo_hub.py -->``
  ``<!-- END_AUTOGEN section_id=pmo_stakeholder_index_v1 sha256=<hex> -->``

- **Refuse-to-write** when both markers are absent or unbalanced.
- **Drift detection** via END marker `sha256=<hex>` of rendered body. On next
  run, mismatch → exit non-zero with ``AUTOGEN_DRIFT_DETECTED``.
- **Idempotent** when inputs are unchanged.
- **Hand-author safety**: content above BEGIN and below END is never touched.

Usage::

    py scripts/render_pmo_hub.py                # full write (idempotent)
    py scripts/render_pmo_hub.py --check-only   # exit 1 on drift; never writes
    py scripts/render_pmo_hub.py --dry-run      # print rendered body to stdout
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

HUB_PATH = (
    REPO_ROOT
    / "docs"
    / "references"
    / "hlk"
    / "v3.0"
    / "Admin"
    / "O5-1"
    / "Operations"
    / "PMO"
    / "TOPIC_PMO_CLIENT_DELIVERY_HUB.md"
)
GOIPOI_CSV = REPO_ROOT / "docs" / "references" / "hlk" / "compliance" / "GOI_POI_REGISTER.csv"
DISCIPLINES_CSV = REPO_ROOT / "docs" / "references" / "hlk" / "compliance" / "ADVISER_ENGAGEMENT_DISCIPLINES.csv"
QUESTIONS_CSV = REPO_ROOT / "docs" / "references" / "hlk" / "compliance" / "ADVISER_OPEN_QUESTIONS.csv"
PROGRAM_REGISTRY_CSV = REPO_ROOT / "docs" / "references" / "hlk" / "compliance" / "dimensions" / "PROGRAM_REGISTRY.csv"

SECTION_ID = "pmo_stakeholder_index_v1"
BEGIN_MARKER = re.compile(
    rf"<!--\s*BEGIN_AUTOGEN\s+section_id={re.escape(SECTION_ID)}\s+generated_by=[^>]*-->",
)
END_MARKER = re.compile(
    rf"<!--\s*END_AUTOGEN\s+section_id={re.escape(SECTION_ID)}(?:\s+sha256=[a-f0-9]{{64}})?\s*-->",
)
END_MARKER_TEMPLATE = "<!-- END_AUTOGEN section_id={section_id} sha256={sha} -->"


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        return []
    with path.open(encoding="utf-8", newline="") as fh:
        return [dict(r) for r in csv.DictReader(fh)]


def _md_escape(value: str) -> str:
    """Escape pipes inside table cells; preserve everything else."""
    return (value or "").replace("|", "\\|").replace("\n", " ").strip()


def render_body() -> str:
    """Build the auto-gen body text. Returns the inner content (no markers)."""
    goipoi = _read_csv(GOIPOI_CSV)
    disciplines = {(d.get("discipline_id") or "").strip(): d for d in _read_csv(DISCIPLINES_CSV)}
    programs = {(p.get("program_id") or "").strip(): p for p in _read_csv(PROGRAM_REGISTRY_CSV)}
    questions = _read_csv(QUESTIONS_CSV)

    # Count open questions per ref_id (for stakeholder load).
    q_by_ref: dict[str, int] = {}
    for q in questions:
        for col in ("poi_ref_id", "goi_ref_id"):
            ref = (q.get(col) or "").strip()
            if ref:
                q_by_ref[ref] = q_by_ref.get(ref, 0) + 1

    rows: list[str] = []
    rows.append("> **Auto-generated by `scripts/render_pmo_hub.py` from canonical CSVs.** Edit the CSVs (`GOI_POI_REGISTER.csv`, `ADVISER_OPEN_QUESTIONS.csv`, `PROGRAM_REGISTRY.csv`) and re-run; do **not** edit between the BEGIN_AUTOGEN / END_AUTOGEN markers by hand.")
    rows.append("")
    rows.append("| ref_id | class | lens | sensitivity | program_id | open_questions | notes |")
    rows.append("|:-------|:------|:-----|:------------|:-----------|:--------------:|:------|")
    for r in sorted(goipoi, key=lambda x: x.get("ref_id", "")):
        ref = (r.get("ref_id") or "").strip()
        if not ref:
            continue
        klass = _md_escape(r.get("class") or "")
        lens = _md_escape(r.get("lens") or "")
        sens = _md_escape(r.get("sensitivity") or "")
        prog = _md_escape(r.get("program_id") or "")
        notes = _md_escape(r.get("notes") or "")
        if len(notes) > 120:
            notes = notes[:117] + "..."
        nq = q_by_ref.get(ref, 0)
        rows.append(f"| `{ref}` | `{klass}` | `{lens}` | `{sens}` | `{prog}` | {nq} | {notes} |")
    rows.append("")
    rows.append(f"**Source counts:** {len(goipoi)} GOI/POI rows; {len(programs)} programs; {len(questions)} open questions.")
    return "\n".join(rows) + "\n"


def render_section_with_markers(body: str) -> tuple[str, str]:
    """Wrap body in BEGIN/END markers; return (full_section, sha256_hex)."""
    sha = hashlib.sha256(body.encode("utf-8")).hexdigest()
    full = (
        f"<!-- BEGIN_AUTOGEN section_id={SECTION_ID} generated_by=scripts/render_pmo_hub.py -->\n"
        + body
        + END_MARKER_TEMPLATE.format(section_id=SECTION_ID, sha=sha)
        + "\n"
    )
    return full, sha


def find_markers(text: str) -> tuple[int, int] | None:
    begin = BEGIN_MARKER.search(text)
    end = END_MARKER.search(text)
    if begin is None or end is None:
        return None
    if begin.end() > end.start():
        return None
    return begin.start(), end.end()


def cmd_check_only(text: str) -> int:
    print("\n  PMO hub auto-gen marker check")
    print("  " + "=" * 40)
    span = find_markers(text)
    if span is None:
        print(f"  FAIL: MARKER_NOT_FOUND — both markers required for section_id={SECTION_ID}")
        return 1
    body = render_body()
    expected_sha = hashlib.sha256(body.encode("utf-8")).hexdigest()
    end_match = END_MARKER.search(text)
    if end_match is None:
        print("  FAIL: END marker missing")
        return 1
    end_text = end_match.group(0)
    sha_in_end = re.search(r"sha256=([a-f0-9]{64})", end_text)
    if sha_in_end is None:
        print("  WARN: END marker has no sha256 yet (first run not committed)")
        return 0
    if sha_in_end.group(1) != expected_sha:
        print(f"  FAIL: AUTOGEN_DRIFT_DETECTED — body sha256 changed")
        print(f"    expected (current canonical CSV inputs): {expected_sha[:16]}...")
        print(f"    found in END marker:                      {sha_in_end.group(1)[:16]}...")
        print("    Run `py scripts/render_pmo_hub.py` to refresh, then commit.")
        return 1
    print(f"  PASS: section_id={SECTION_ID}; body sha256 matches ({expected_sha[:16]}...)")
    return 0


def cmd_dry_run() -> int:
    body = render_body()
    sys.stdout.write(body)
    return 0


def cmd_write(text: str) -> int:
    span = find_markers(text)
    if span is None:
        sys.stderr.write(
            f"render_pmo_hub: MARKER_NOT_FOUND — both BEGIN_AUTOGEN and END_AUTOGEN markers must "
            f"exist for section_id={SECTION_ID} in {HUB_PATH.relative_to(REPO_ROOT)}\n"
            "Operator runbook:\n"
            "  Insert the markers around the stakeholder index table:\n"
            f"    <!-- BEGIN_AUTOGEN section_id={SECTION_ID} generated_by=scripts/render_pmo_hub.py -->\n"
            f"    <!-- END_AUTOGEN section_id={SECTION_ID} sha256=PLACEHOLDER -->\n"
            "  then re-run this script.\n"
        )
        return 1
    start, end = span
    body = render_body()
    section, sha = render_section_with_markers(body)
    new_text = text[:start] + section + text[end:]
    if new_text == text:
        print(f"render_pmo_hub: idempotent — no change (sha256={sha[:16]}...)")
        return 0
    HUB_PATH.write_text(new_text, encoding="utf-8")
    print(f"render_pmo_hub: wrote {HUB_PATH.relative_to(REPO_ROOT)} (body sha256={sha[:16]}...)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Verify markers exist and END sha256 matches current rendered body",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print rendered body to stdout without touching the file",
    )
    args = parser.parse_args(argv)

    if not HUB_PATH.is_file():
        sys.stderr.write(f"render_pmo_hub: missing {HUB_PATH}\n")
        return 2

    text = HUB_PATH.read_text(encoding="utf-8")

    if args.dry_run:
        return cmd_dry_run()
    if args.check_only:
        return cmd_check_only(text)
    return cmd_write(text)


if __name__ == "__main__":
    raise SystemExit(main())
